### ISSUE TITLE
Create server security

### ISSUE THREAD

**Issue by Merlin-55** [Stiehl-seine-Perlen/Benevolo#20]
>I as security expert Severin want to secure our server to protect us from attacks.

### Acceptance criteria
- it is not possible to connect via password authentication
- root is restricted
- we have an additional user

### Subtasks
- [x] disable ssh password login 
- [x] restrict root access
- [x] create additional user 
- [x] new user is sudoer
- [x] Fail2Ban is installed

**Comment by MatthiasRaimann** [comment]
@DanielMehlber bitte prüfen :)

**Comment by DanielMehlber** [comment]
Ist fail2ban installiert & konfiguriert?

Nutzt bitte die Gelegenheit dazu, euch ein bisschen zu Informieren wie man einen Linux Server **richtig** absichert. Das braucht man immer, wenn man im Informatik-Umfeld tätig ist.

Die ausgelieferten Ubuntu Images sind unkonfiguriert nicht abgesichert und können geknackt werden. Verlasst euch also nicht darauf.

**Comment by MatthiasRaimann** [comment]
![0C97014E-9CA1-44D3-AB2F-C0AA558CF411](https://user-images.githubusercontent.com/33811156/231146061-d2f2afa7-2caa-4f44-8cd0-d349e970eafa.png)

@DanielMehlber
