### ISSUE TITLE
Define business master data

### ISSUE THREAD

**Issue by Merlin-55** [Stiehl-seine-Perlen/Benevolo#9]
>I as product owner Olaf want to have a diagram that documents the data scheme of our application to be able to configure our database.

### Acceptance Criteria

- all business entities are defined with their attributes

#### Business Objects

- just browsing visitors
- customer with account
- customer with account that manages club pages
- invoice (ingoing)
- invoice (outgoing)
- project
- event
- member
- financial account
- transaction

### Subtasks

- [x] create ERD document
- [x] present ERD to BP team
- [x] present ERD to A team

**Comment by Merlin-55** [comment]
Created a [new branch](https://github.com/Stiehl-seine-Perlen/camaradrIO/blob/story/bp-9/erd.md) to mitigate this story.
